services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
    - postgres
    - redis
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      REDIS_ADDR: ${REDIS_ADDR}
      JWT_SECRET: ${JWT_SECRET}
    ports:
    - "8080:8080"

